const PinyinData = {
  shengmu: [
    { pinyin: 'b', name: '波' },
    { pinyin: 'p', name: '坡' },
    { pinyin: 'm', name: '摸' },
    { pinyin: 'f', name: '佛' },
    { pinyin: 'd', name: '得' },
    { pinyin: 't', name: '特' },
    { pinyin: 'n', name: '讷' },
    { pinyin: 'l', name: '勒' },
    { pinyin: 'g', name: '哥' },
    { pinyin: 'k', name: '科' },
    { pinyin: 'h', name: '喝' },
    { pinyin: 'j', name: '基' },
    { pinyin: 'q', name: '欺' },
    { pinyin: 'x', name: '希' },
    { pinyin: 'zh', name: '知' },
    { pinyin: 'ch', name: '吃' },
    { pinyin: 'sh', name: '诗' },
    { pinyin: 'r', name: '日' },
    { pinyin: 'z', name: '资' },
    { pinyin: 'c', name: '雌' },
    { pinyin: 's', name: '思' },
    { pinyin: 'y', name: '医' },
    { pinyin: 'w', name: '屋' }
  ],

  yunmu: {
    dan: [
      { pinyin: 'a', name: '啊' },
      { pinyin: 'o', name: '喔' },
      { pinyin: 'e', name: '鹅' },
      { pinyin: 'i', name: '衣' },
      { pinyin: 'u', name: '乌' },
      { pinyin: 'ü', name: '迂' }
    ],
    fu: [
      { pinyin: 'ai', name: '哀' },
      { pinyin: 'ei', name: '诶' },
      { pinyin: 'ui', name: '威' },
      { pinyin: 'ao', name: '凹' },
      { pinyin: 'ou', name: '欧' },
      { pinyin: 'iu', name: '优' },
      { pinyin: 'ie', name: '耶' },
      { pinyin: 'üe', name: '约' },
      { pinyin: 'er', name: '儿' }
    ],
    qianbi: [
      { pinyin: 'an', name: '安' },
      { pinyin: 'en', name: '恩' },
      { pinyin: 'in', name: '因' },
      { pinyin: 'un', name: '温' },
      { pinyin: 'ün', name: '晕' }
    ],
    houbi: [
      { pinyin: 'ang', name: '昂' },
      { pinyin: 'eng', name: '亨的韵母' },
      { pinyin: 'ing', name: '英' },
      { pinyin: 'ong', name: '轰的韵母' }
    ]
  },

  zhengti: [
    { pinyin: 'zhi', name: '知' },
    { pinyin: 'chi', name: '吃' },
    { pinyin: 'shi', name: '诗' },
    { pinyin: 'ri', name: '日' },
    { pinyin: 'zi', name: '资' },
    { pinyin: 'ci', name: '雌' },
    { pinyin: 'si', name: '思' },
    { pinyin: 'yi', name: '衣' },
    { pinyin: 'wu', name: '乌' },
    { pinyin: 'yu', name: '迂' },
    { pinyin: 'ye', name: '耶' },
    { pinyin: 'yue', name: '约' },
    { pinyin: 'yuan', name: '冤' },
    { pinyin: 'yin', name: '因' },
    { pinyin: 'yun', name: '晕' },
    { pinyin: 'ying', name: '英' }
  ],

  liangpin: [
    { pinyin: 'ba', name: '八', example: '爸爸' },
    { pinyin: 'ma', name: '妈', example: '妈妈' },
    { pinyin: 'da', name: '打', example: '打开' },
    { pinyin: 'ta', name: '他', example: '他们' },
    { pinyin: 'na', name: '那', example: '那里' },
    { pinyin: 'la', name: '拉', example: '拉手' },
    { pinyin: 'ga', name: '嘎', example: '嘎嘎' },
    { pinyin: 'ka', name: '卡', example: '卡片' },
    { pinyin: 'ha', name: '哈', example: '哈哈' },
    { pinyin: 'jia', name: '家', example: '回家' },
    { pinyin: 'qia', name: '恰', example: '恰好' },
    { pinyin: 'xia', name: '下', example: '下面' },
    { pinyin: 'zha', name: '炸', example: '爆炸' },
    { pinyin: 'cha', name: '查', example: '检查' },
    { pinyin: 'sha', name: '沙', example: '沙子' },
    { pinyin: 'za', name: '杂', example: '杂志' },
    { pinyin: 'ca', name: '擦', example: '擦手' },
    { pinyin: 'sa', name: '洒', example: '洒水' },
    { pinyin: 'ya', name: '呀', example: '好呀' },
    { pinyin: 'wa', name: '挖', example: '挖土' },
    { pinyin: 'bo', name: '波', example: '波浪' },
    { pinyin: 'po', name: '坡', example: '山坡' },
    { pinyin: 'mo', name: '摸', example: '摸摸' },
    { pinyin: 'fo', name: '佛', example: '佛像' },
    { pinyin: 'duo', name: '多', example: '很多' },
    { pinyin: 'tuo', name: '脱', example: '脱下' },
    { pinyin: 'nuo', name: '挪', example: '挪动' },
    { pinyin: 'luo', name: '落', example: '落下' },
    { pinyin: 'guo', name: '国', example: '中国' },
    { pinyin: 'kuo', name: '阔', example: '宽阔' },
    { pinyin: 'huo', name: '活', example: '生活' },
    { pinyin: 'zuo', name: '做', example: '做事' },
    { pinyin: 'cuo', name: '错', example: '错误' },
    { pinyin: 'suo', name: '所', example: '所以' },
    { pinyin: 'wo', name: '我', example: '我们' }
  ],

  sanpin: [
    { pinyin: 'hua', name: '花', example: '花朵' },
    { pinyin: 'gua', name: '瓜', example: '西瓜' },
    { pinyin: 'kua', name: '夸', example: '夸奖' },
    { pinyin: 'zhua', name: '抓', example: '抓住' },
    { pinyin: 'chua', name: '欻', example: '欻拉' },
    { pinyin: 'shua', name: '刷', example: '刷牙' },
    { pinyin: 'pian', name: '片', example: '一片' },
    { pinyin: 'mian', name: '面', example: '面条' },
    { pinyin: 'tian', name: '天', example: '天空' },
    { pinyin: 'nian', name: '年', example: '新年' },
    { pinyin: 'lian', name: '连', example: '连接' },
    { pinyin: 'bian', name: '变', example: '变化' },
    { pinyin: 'jian', name: '见', example: '看见' },
    { pinyin: 'qian', name: '前', example: '前面' },
    { pinyin: 'xian', name: '先', example: '先生' }
  ]
};

const ChineseChars = {
  level1: [
    { char: '一', pinyin: 'yī', meaning: '数字1' },
    { char: '二', pinyin: 'èr', meaning: '数字2' },
    { char: '三', pinyin: 'sān', meaning: '数字3' },
    { char: '四', pinyin: 'sì', meaning: '数字4' },
    { char: '五', pinyin: 'wǔ', meaning: '数字5' },
    { char: '六', pinyin: 'liù', meaning: '数字6' },
    { char: '七', pinyin: 'qī', meaning: '数字7' },
    { char: '八', pinyin: 'bā', meaning: '数字8' },
    { char: '九', pinyin: 'jiǔ', meaning: '数字9' },
    { char: '十', pinyin: 'shí', meaning: '数字10' },
    { char: '百', pinyin: 'bǎi', meaning: '一百' },
    { char: '千', pinyin: 'qiān', meaning: '一千' },
    { char: '万', pinyin: 'wàn', meaning: '一万' },
    { char: '上', pinyin: 'shàng', meaning: '上面' },
    { char: '下', pinyin: 'xià', meaning: '下面' },
    { char: '左', pinyin: 'zuǒ', meaning: '左边' },
    { char: '右', pinyin: 'yòu', meaning: '右边' },
    { char: '前', pinyin: 'qián', meaning: '前面' },
    { char: '后', pinyin: 'hòu', meaning: '后面' },
    { char: '里', pinyin: 'lǐ', meaning: '里面' },
    { char: '外', pinyin: 'wài', meaning: '外面' },
    { char: '中', pinyin: 'zhōng', meaning: '中间' },
    { char: '间', pinyin: 'jiān', meaning: '之间' },
    { char: '东', pinyin: 'dōng', meaning: '东方' },
    { char: '西', pinyin: 'xī', meaning: '西方' },
    { char: '南', pinyin: 'nán', meaning: '南方' },
    { char: '北', pinyin: 'běi', meaning: '北方' },
    { char: '人', pinyin: 'rén', meaning: '人类' },
    { char: '口', pinyin: 'kǒu', meaning: '嘴巴' },
    { char: '手', pinyin: 'shǒu', meaning: '双手' },
    { char: '足', pinyin: 'zú', meaning: '脚' },
    { char: '头', pinyin: 'tóu', meaning: '脑袋' },
    { char: '目', pinyin: 'mù', meaning: '眼睛' },
    { char: '耳', pinyin: 'ěr', meaning: '耳朵' },
    { char: '舌', pinyin: 'shé', meaning: '舌头' },
    { char: '牙', pinyin: 'yá', meaning: '牙齿' },
    { char: '心', pinyin: 'xīn', meaning: '心脏' },
    { char: '身', pinyin: 'shēn', meaning: '身体' },
    { char: '体', pinyin: 'tǐ', meaning: '身体' },
    { char: '日', pinyin: 'rì', meaning: '太阳' },
    { char: '月', pinyin: 'yuè', meaning: '月亮' },
    { char: '水', pinyin: 'shuǐ', meaning: '喝水' },
    { char: '火', pinyin: 'huǒ', meaning: '火焰' },
    { char: '山', pinyin: 'shān', meaning: '高山' },
    { char: '石', pinyin: 'shí', meaning: '石头' },
    { char: '田', pinyin: 'tián', meaning: '田地' },
    { char: '土', pinyin: 'tǔ', meaning: '土地' },
    { char: '天', pinyin: 'tiān', meaning: '天空' },
    { char: '地', pinyin: 'dì', meaning: '大地' },
    { char: '云', pinyin: 'yún', meaning: '白云' },
    { char: '雨', pinyin: 'yǔ', meaning: '下雨' },
    { char: '风', pinyin: 'fēng', meaning: '大风' },
    { char: '雪', pinyin: 'xuě', meaning: '雪花' },
    { char: '门', pinyin: 'mén', meaning: '大门' },
    { char: '窗', pinyin: 'chuāng', meaning: '窗户' },
    { char: '房', pinyin: 'fáng', meaning: '房子' },
    { char: '屋', pinyin: 'wū', meaning: '房屋' },
    { char: '家', pinyin: 'jiā', meaning: '回家' },
    { char: '床', pinyin: 'chuáng', meaning: '睡觉' },
    { char: '桌', pinyin: 'zhuō', meaning: '桌子' },
    { char: '椅', pinyin: 'yǐ', meaning: '椅子' },
    { char: '灯', pinyin: 'dēng', meaning: '灯光' },
    { char: '书', pinyin: 'shū', meaning: '书本' },
    { char: '本', pinyin: 'běn', meaning: '本子' },
    { char: '笔', pinyin: 'bǐ', meaning: '铅笔' },
    { char: '刀', pinyin: 'dāo', meaning: '小刀' },
    { char: '牛', pinyin: 'niú', meaning: '奶牛' },
    { char: '马', pinyin: 'mǎ', meaning: '骏马' },
    { char: '羊', pinyin: 'yáng', meaning: '绵羊' },
    { char: '鸡', pinyin: 'jī', meaning: '公鸡' },
    { char: '鸭', pinyin: 'yā', meaning: '鸭子' },
    { char: '鹅', pinyin: 'é', meaning: '白鹅' },
    { char: '狗', pinyin: 'gǒu', meaning: '小狗' },
    { char: '猫', pinyin: 'māo', meaning: '小猫' },
    { char: '鱼', pinyin: 'yú', meaning: '小鱼' },
    { char: '鸟', pinyin: 'niǎo', meaning: '小鸟' },
    { char: '大', pinyin: 'dà', meaning: '大小' },
    { char: '小', pinyin: 'xiǎo', meaning: '小鸟' },
    { char: '多', pinyin: 'duō', meaning: '很多' },
    { char: '少', pinyin: 'shǎo', meaning: '多少' },
    { char: '来', pinyin: 'lái', meaning: '过来' },
    { char: '去', pinyin: 'qù', meaning: '回去' },
    { char: '出', pinyin: 'chū', meaning: '出去' },
    { char: '入', pinyin: 'rù', meaning: '进入' },
    { char: '开', pinyin: 'kāi', meaning: '开门' },
    { char: '关', pinyin: 'guān', meaning: '关门' },
    { char: '坐', pinyin: 'zuò', meaning: '坐下' },
    { char: '立', pinyin: 'lì', meaning: '站立' },
    { char: '高', pinyin: 'gāo', meaning: '高兴' },
    { char: '低', pinyin: 'dī', meaning: '低头' },
    { char: '好', pinyin: 'hǎo', meaning: '好人' },
    { char: '坏', pinyin: 'huài', meaning: '坏人' },
    { char: '快', pinyin: 'kuài', meaning: '快乐' },
    { char: '慢', pinyin: 'màn', meaning: '慢慢' },
    { char: '早', pinyin: 'zǎo', meaning: '早上' },
    { char: '晚', pinyin: 'wǎn', meaning: '晚上' },
    { char: '今', pinyin: 'jīn', meaning: '今天' },
    { char: '明', pinyin: 'míng', meaning: '明天' },
    { char: '学', pinyin: 'xué', meaning: '学习' },
    { char: '习', pinyin: 'xí', meaning: '练习' }
  ],

  level2: [
    { char: '爸', pinyin: 'bà', meaning: '爸爸' },
    { char: '妈', pinyin: 'mā', meaning: '妈妈' },
    { char: '爷', pinyin: 'yé', meaning: '爷爷' },
    { char: '奶', pinyin: 'nǎi', meaning: '奶奶' },
    { char: '哥', pinyin: 'gē', meaning: '哥哥' },
    { char: '弟', pinyin: 'dì', meaning: '弟弟' },
    { char: '姐', pinyin: 'jiě', meaning: '姐姐' },
    { char: '妹', pinyin: 'mèi', meaning: '妹妹' },
    { char: '儿', pinyin: 'ér', meaning: '儿子' },
    { char: '女', pinyin: 'nǚ', meaning: '女儿' },
    { char: '父', pinyin: 'fù', meaning: '父亲' },
    { char: '母', pinyin: 'mǔ', meaning: '母亲' },
    { char: '子', pinyin: 'zǐ', meaning: '孩子' },
    { char: '孙', pinyin: 'sūn', meaning: '孙子' },
    { char: '米', pinyin: 'mǐ', meaning: '大米' },
    { char: '面', pinyin: 'miàn', meaning: '面条' },
    { char: '饭', pinyin: 'fàn', meaning: '吃饭' },
    { char: '菜', pinyin: 'cài', meaning: '蔬菜' },
    { char: '汤', pinyin: 'tāng', meaning: '喝汤' },
    { char: '果', pinyin: 'guǒ', meaning: '水果' },
    { char: '苹', pinyin: 'píng', meaning: '苹果' },
    { char: '桃', pinyin: 'táo', meaning: '桃子' },
    { char: '瓜', pinyin: 'guā', meaning: '西瓜' },
    { char: '豆', pinyin: 'dòu', meaning: '豆子' },
    { char: '蛋', pinyin: 'dàn', meaning: '鸡蛋' },
    { char: '肉', pinyin: 'ròu', meaning: '猪肉' },
    { char: '糖', pinyin: 'táng', meaning: '糖果' },
    { char: '李', pinyin: 'lǐ', meaning: '李子' },
    { char: '杏', pinyin: 'xìng', meaning: '杏子' },
    { char: '枣', pinyin: 'zǎo', meaning: '红枣' },
    { char: '梨', pinyin: 'lí', meaning: '梨子' },
    { char: '柿', pinyin: 'shì', meaning: '柿子' },
    { char: '桔', pinyin: 'jú', meaning: '桔子' },
    { char: '橙', pinyin: 'chéng', meaning: '橙子' },
    { char: '香', pinyin: 'xiāng', meaning: '香甜' },
    { char: '蕉', pinyin: 'jiāo', meaning: '香蕉' },
    { char: '发', pinyin: 'fà', meaning: '头发' },
    { char: '眼', pinyin: 'yǎn', meaning: '眼睛' },
    { char: '鼻', pinyin: 'bí', meaning: '鼻子' },
    { char: '嘴', pinyin: 'zuǐ', meaning: '嘴巴' },
    { char: '唇', pinyin: 'chún', meaning: '嘴唇' },
    { char: '眉', pinyin: 'méi', meaning: '眉毛' },
    { char: '脸', pinyin: 'liǎn', meaning: '脸蛋' },
    { char: '颈', pinyin: 'jǐng', meaning: '头颈' },
    { char: '肩', pinyin: 'jiān', meaning: '肩膀' },
    { char: '臂', pinyin: 'bì', meaning: '手臂' },
    { char: '指', pinyin: 'zhǐ', meaning: '手指' },
    { char: '掌', pinyin: 'zhǎng', meaning: '手掌' },
    { char: '红', pinyin: 'hóng', meaning: '红色' },
    { char: '黄', pinyin: 'huáng', meaning: '黄色' },
    { char: '蓝', pinyin: 'lán', meaning: '蓝色' },
    { char: '绿', pinyin: 'lǜ', meaning: '绿色' },
    { char: '白', pinyin: 'bái', meaning: '白色' },
    { char: '黑', pinyin: 'hēi', meaning: '黑色' },
    { char: '灰', pinyin: 'huī', meaning: '灰色' },
    { char: '彩', pinyin: 'cǎi', meaning: '彩色' },
    { char: '晴', pinyin: 'qíng', meaning: '晴天' },
    { char: '阴', pinyin: 'yīn', meaning: '阴天' },
    { char: '雷', pinyin: 'léi', meaning: '打雷' },
    { char: '电', pinyin: 'diàn', meaning: '闪电' },
    { char: '虹', pinyin: 'hóng', meaning: '彩虹' },
    { char: '虎', pinyin: 'hǔ', meaning: '老虎' },
    { char: '狮', pinyin: 'shī', meaning: '狮子' },
    { char: '熊', pinyin: 'xióng', meaning: '熊猫' },
    { char: '狼', pinyin: 'láng', meaning: '野狼' },
    { char: '鹿', pinyin: 'lù', meaning: '小鹿' },
    { char: '兔', pinyin: 'tù', meaning: '兔子' },
    { char: '猴', pinyin: 'hóu', meaning: '猴子' },
    { char: '猪', pinyin: 'zhū', meaning: '小猪' },
    { char: '象', pinyin: 'xiàng', meaning: '大象' },
    { char: '水', pinyin: 'shuǐ', meaning: '开水' },
    { char: '饭', pinyin: 'fàn', meaning: '米饭' },
    { char: '菜', pinyin: 'cài', meaning: '青菜' },
    { char: '汤', pinyin: 'tāng', meaning: '喝汤' },
    { char: '米', pinyin: 'mǐ', meaning: '小米' },
    { char: '面', pinyin: 'miàn', meaning: '面包' },
    { char: '蛋', pinyin: 'dàn', meaning: '鸭蛋' },
    { char: '肉', pinyin: 'ròu', meaning: '牛肉' },
    { char: '糖', pinyin: 'táng', meaning: '白糖' },
    { char: '苹', pinyin: 'píng', meaning: '苹果树' },
    { char: '李', pinyin: 'lǐ', meaning: '李子' },
    { char: '杏', pinyin: 'xìng', meaning: '杏花' },
    { char: '枣', pinyin: 'zǎo', meaning: '枣树' },
    { char: '梨', pinyin: 'lí', meaning: '鸭梨' },
    { char: '柿', pinyin: 'shì', meaning: '柿子' },
    { char: '桔', pinyin: 'jú', meaning: '桔子' },
    { char: '橙', pinyin: 'chéng', meaning: '橙子' },
    { char: '香', pinyin: 'xiāng', meaning: '香水' },
    { char: '蕉', pinyin: 'jiāo', meaning: '香蕉' },
    { char: '红', pinyin: 'hóng', meaning: '红花' },
    { char: '黄', pinyin: 'huáng', meaning: '黄花' },
    { char: '蓝', pinyin: 'lán', meaning: '蓝天' },
    { char: '绿', pinyin: 'lǜ', meaning: '绿叶' },
    { char: '白', pinyin: 'bái', meaning: '白云' },
    { char: '黑', pinyin: 'hēi', meaning: '黑夜' },
    { char: '灰', pinyin: 'huī', meaning: '灰色' },
    { char: '彩', pinyin: 'cǎi', meaning: '彩虹' },
    { char: '晴', pinyin: 'qíng', meaning: '天晴' },
    { char: '阴', pinyin: 'yīn', meaning: '阴天' },
    { char: '雷', pinyin: 'léi', meaning: '雷声' },
    { char: '电', pinyin: 'diàn', meaning: '电视' }
  ],

  level3: [
    { char: '走', pinyin: 'zǒu', meaning: '走路' },
    { char: '跑', pinyin: 'pǎo', meaning: '跑步' },
    { char: '跳', pinyin: 'tiào', meaning: '跳高' },
    { char: '飞', pinyin: 'fēi', meaning: '飞机' },
    { char: '游', pinyin: 'yóu', meaning: '游泳' },
    { char: '爬', pinyin: 'pá', meaning: '爬山' },
    { char: '站', pinyin: 'zhàn', meaning: '站立' },
    { char: '躺', pinyin: 'tǎng', meaning: '躺下' },
    { char: '蹲', pinyin: 'dūn', meaning: '蹲下' },
    { char: '看', pinyin: 'kàn', meaning: '看见' },
    { char: '听', pinyin: 'tīng', meaning: '听见' },
    { char: '说', pinyin: 'shuō', meaning: '说话' },
    { char: '读', pinyin: 'dú', meaning: '读书' },
    { char: '写', pinyin: 'xiě', meaning: '写字' },
    { char: '画', pinyin: 'huà', meaning: '画画' },
    { char: '唱', pinyin: 'chàng', meaning: '唱歌' },
    { char: '吃', pinyin: 'chī', meaning: '吃饭' },
    { char: '喝', pinyin: 'hē', meaning: '喝水' },
    { char: '花', pinyin: 'huā', meaning: '花朵' },
    { char: '草', pinyin: 'cǎo', meaning: '小草' },
    { char: '树', pinyin: 'shù', meaning: '大树' },
    { char: '木', pinyin: 'mù', meaning: '木头' },
    { char: '叶', pinyin: 'yè', meaning: '树叶' },
    { char: '枝', pinyin: 'zhī', meaning: '树枝' },
    { char: '根', pinyin: 'gēn', meaning: '树根' },
    { char: '林', pinyin: 'lín', meaning: '树林' },
    { char: '森', pinyin: 'sēn', meaning: '森林' },
    { char: '苗', pinyin: 'miáo', meaning: '禾苗' },
    { char: '种', pinyin: 'zhòng', meaning: '种树' },
    { char: '昨', pinyin: 'zuó', meaning: '昨天' },
    { char: '春', pinyin: 'chūn', meaning: '春天' },
    { char: '夏', pinyin: 'xià', meaning: '夏天' },
    { char: '秋', pinyin: 'qiū', meaning: '秋天' },
    { char: '冬', pinyin: 'dōng', meaning: '冬天' },
    { char: '年', pinyin: 'nián', meaning: '新年' },
    { char: '节', pinyin: 'jié', meaning: '节日' },
    { char: '周', pinyin: 'zhōu', meaning: '一周' },
    { char: '时', pinyin: 'shí', meaning: '时间' },
    { char: '分', pinyin: 'fēn', meaning: '分钟' },
    { char: '秒', pinyin: 'miǎo', meaning: '秒钟' },
    { char: '城', pinyin: 'chéng', meaning: '城市' },
    { char: '乡', pinyin: 'xiāng', meaning: '乡村' },
    { char: '村', pinyin: 'cūn', meaning: '村子' },
    { char: '路', pinyin: 'lù', meaning: '马路' },
    { char: '桥', pinyin: 'qiáo', meaning: '大桥' },
    { char: '河', pinyin: 'hé', meaning: '小河' },
    { char: '湖', pinyin: 'hú', meaning: '湖水' },
    { char: '海', pinyin: 'hǎi', meaning: '大海' },
    { char: '江', pinyin: 'jiāng', meaning: '长江' },
    { char: '岸', pinyin: 'àn', meaning: '岸边' },
    { char: '钟', pinyin: 'zhōng', meaning: '时钟' },
    { char: '表', pinyin: 'biǎo', meaning: '手表' },
    { char: '伞', pinyin: 'sǎn', meaning: '雨伞' },
    { char: '镜', pinyin: 'jìng', meaning: '镜子' },
    { char: '杯', pinyin: 'bēi', meaning: '杯子' },
    { char: '碗', pinyin: 'wǎn', meaning: '饭碗' },
    { char: '盘', pinyin: 'pán', meaning: '盘子' },
    { char: '勺', pinyin: 'sháo', meaning: '勺子' },
    { char: '筷', pinyin: 'kuài', meaning: '筷子' },
    { char: '瓶', pinyin: 'píng', meaning: '瓶子' },
    { char: '走', pinyin: 'zǒu', meaning: '走开' },
    { char: '跑', pinyin: 'pǎo', meaning: '快跑' },
    { char: '跳', pinyin: 'tiào', meaning: '跳舞' },
    { char: '飞', pinyin: 'fēi', meaning: '飞翔' },
    { char: '游', pinyin: 'yóu', meaning: '游戏' },
    { char: '爬', pinyin: 'pá', meaning: '爬行' },
    { char: '站', pinyin: 'zhàn', meaning: '车站' },
    { char: '躺', pinyin: 'tǎng', meaning: '躺着' },
    { char: '蹲', pinyin: 'dūn', meaning: '蹲着' },
    { char: '看', pinyin: 'kàn', meaning: '看书' },
    { char: '听', pinyin: 'tīng', meaning: '听歌' },
    { char: '说', pinyin: 'shuō', meaning: '小说' },
    { char: '读', pinyin: 'dú', meaning: '阅读' },
    { char: '写', pinyin: 'xiě', meaning: '书写' },
    { char: '画', pinyin: 'huà', meaning: '图画' },
    { char: '唱', pinyin: 'chàng', meaning: '演唱' },
    { char: '吃', pinyin: 'chī', meaning: '吃喝' },
    { char: '喝', pinyin: 'hē', meaning: '喝酒' },
    { char: '花', pinyin: 'huā', meaning: '鲜花' },
    { char: '草', pinyin: 'cǎo', meaning: '草地' },
    { char: '树', pinyin: 'shù', meaning: '种树' },
    { char: '木', pinyin: 'mù', meaning: '木材' },
    { char: '叶', pinyin: 'yè', meaning: '绿叶' },
    { char: '枝', pinyin: 'zhī', meaning: '枝条' },
    { char: '根', pinyin: 'gēn', meaning: '根本' },
    { char: '林', pinyin: 'lín', meaning: '森林' },
    { char: '森', pinyin: 'sēn', meaning: '森严' },
    { char: '苗', pinyin: 'miáo', meaning: '树苗' },
    { char: '种', pinyin: 'zhǒng', meaning: '种子' },
    { char: '昨', pinyin: 'zuó', meaning: '昨日' },
    { char: '春', pinyin: 'chūn', meaning: '春雨' },
    { char: '夏', pinyin: 'xià', meaning: '夏季' },
    { char: '秋', pinyin: 'qiū', meaning: '秋天' },
    { char: '冬', pinyin: 'dōng', meaning: '冬天' },
    { char: '年', pinyin: 'nián', meaning: '年龄' },
    { char: '节', pinyin: 'jié', meaning: '节约' }
  ],

  level4: [
    { char: '高', pinyin: 'gāo', meaning: '高大' },
    { char: '矮', pinyin: 'ǎi', meaning: '矮小' },
    { char: '胖', pinyin: 'pàng', meaning: '肥胖' },
    { char: '瘦', pinyin: 'shòu', meaning: '瘦弱' },
    { char: '长', pinyin: 'cháng', meaning: '长度' },
    { char: '短', pinyin: 'duǎn', meaning: '短小' },
    { char: '粗', pinyin: 'cū', meaning: '粗壮' },
    { char: '细', pinyin: 'xì', meaning: '细长' },
    { char: '新', pinyin: 'xīn', meaning: '新鲜' },
    { char: '旧', pinyin: 'jiù', meaning: '破旧' },
    { char: '美', pinyin: 'měi', meaning: '美丽' },
    { char: '丑', pinyin: 'chǒu', meaning: '丑陋' },
    { char: '臭', pinyin: 'chòu', meaning: '臭味' },
    { char: '甜', pinyin: 'tián', meaning: '甜蜜' },
    { char: '苦', pinyin: 'kǔ', meaning: '苦味' },
    { char: '冷', pinyin: 'lěng', meaning: '寒冷' },
    { char: '热', pinyin: 'rè', meaning: '炎热' },
    { char: '洗', pinyin: 'xǐ', meaning: '洗手' },
    { char: '刷', pinyin: 'shuā', meaning: '刷牙' },
    { char: '扫', pinyin: 'sǎo', meaning: '扫地' },
    { char: '擦', pinyin: 'cā', meaning: '擦汗' },
    { char: '拖', pinyin: 'tuō', meaning: '拖地' },
    { char: '搬', pinyin: 'bān', meaning: '搬家' },
    { char: '推', pinyin: 'tuī', meaning: '推开' },
    { char: '拉', pinyin: 'lā', meaning: '拉手' },
    { char: '拿', pinyin: 'ná', meaning: '拿起' },
    { char: '放', pinyin: 'fàng', meaning: '放下' },
    { char: '抱', pinyin: 'bào', meaning: '拥抱' },
    { char: '背', pinyin: 'bēi', meaning: '背包' },
    { char: '提', pinyin: 'tí', meaning: '提水' },
    { char: '举', pinyin: 'jǔ', meaning: '举手' },
    { char: '打', pinyin: 'dǎ', meaning: '打球' },
    { char: '拍', pinyin: 'pāi', meaning: '拍手' },
    { char: '踢', pinyin: 'tī', meaning: '踢球' },
    { char: '扔', pinyin: 'rēng', meaning: '扔掉' },
    { char: '接', pinyin: 'jiē', meaning: '接住' },
    { char: '笑', pinyin: 'xiào', meaning: '微笑' },
    { char: '哭', pinyin: 'kū', meaning: '哭泣' },
    { char: '爱', pinyin: 'ài', meaning: '爱心' },
    { char: '恨', pinyin: 'hèn', meaning: '仇恨' },
    { char: '喜', pinyin: 'xǐ', meaning: '喜欢' },
    { char: '欢', pinyin: 'huān', meaning: '欢乐' },
    { char: '兴', pinyin: 'xìng', meaning: '高兴' },
    { char: '难', pinyin: 'nán', meaning: '难过' },
    { char: '过', pinyin: 'guò', meaning: '过去' },
    { char: '生', pinyin: 'shēng', meaning: '生气' },
    { char: '害', pinyin: 'hài', meaning: '害怕' },
    { char: '怕', pinyin: 'pà', meaning: '害怕' },
    { char: '开', pinyin: 'kāi', meaning: '开心' },
    { char: '心', pinyin: 'xīn', meaning: '心情' },
    { char: '个', pinyin: 'gè', meaning: '一个' },
    { char: '只', pinyin: 'zhī', meaning: '一只' },
    { char: '条', pinyin: 'tiáo', meaning: '一条' },
    { char: '把', pinyin: 'bǎ', meaning: '一把' },
    { char: '张', pinyin: 'zhāng', meaning: '一张' },
    { char: '块', pinyin: 'kuài', meaning: '一块' },
    { char: '本', pinyin: 'běn', meaning: '一本' },
    { char: '支', pinyin: 'zhī', meaning: '一支' },
    { char: '件', pinyin: 'jiàn', meaning: '一件' },
    { char: '双', pinyin: 'shuāng', meaning: '一双' },
    { char: '对', pinyin: 'duì', meaning: '一对' },
    { char: '组', pinyin: 'zǔ', meaning: '一组' },
    { char: '群', pinyin: 'qún', meaning: '一群' },
    { char: '堆', pinyin: 'duī', meaning: '一堆' },
    { char: '圆', pinyin: 'yuán', meaning: '圆形' },
    { char: '方', pinyin: 'fāng', meaning: '方形' },
    { char: '扁', pinyin: 'biǎn', meaning: '扁平' },
    { char: '尖', pinyin: 'jiān', meaning: '尖锐' },
    { char: '正', pinyin: 'zhèng', meaning: '正面' },
    { char: '反', pinyin: 'fǎn', meaning: '反面' },
    { char: '弯', pinyin: 'wān', meaning: '弯曲' },
    { char: '直', pinyin: 'zhí', meaning: '直线' },
    { char: '高', pinyin: 'gāo', meaning: '高楼' },
    { char: '矮', pinyin: 'ǎi', meaning: '矮子' },
    { char: '胖', pinyin: 'pàng', meaning: '胖子' },
    { char: '瘦', pinyin: 'shòu', meaning: '瘦子' },
    { char: '长', pinyin: 'zhǎng', meaning: '生长' },
    { char: '短', pinyin: 'duǎn', meaning: '短期' },
    { char: '粗', pinyin: 'cū', meaning: '粗心' },
    { char: '细', pinyin: 'xì', meaning: '细心' },
    { char: '新', pinyin: 'xīn', meaning: '新闻' },
    { char: '旧', pinyin: 'jiù', meaning: '旧书' },
    { char: '好', pinyin: 'hǎo', meaning: '好人' },
    { char: '坏', pinyin: 'huài', meaning: '破坏' },
    { char: '美', pinyin: 'měi', meaning: '美好' },
    { char: '丑', pinyin: 'chǒu', meaning: '丑事' },
    { char: '香', pinyin: 'xiāng', meaning: '香水' },
    { char: '臭', pinyin: 'chòu', meaning: '臭虫' },
    { char: '甜', pinyin: 'tián', meaning: '甜食' },
    { char: '苦', pinyin: 'kǔ', meaning: '辛苦' },
    { char: '冷', pinyin: 'lěng', meaning: '冷水' },
    { char: '热', pinyin: 'rè', meaning: '热水' },
    { char: '洗', pinyin: 'xǐ', meaning: '洗澡' },
    { char: '刷', pinyin: 'shuā', meaning: '刷子' },
    { char: '扫', pinyin: 'sǎo', meaning: '扫墓' }
  ],

  level5: [
    { char: '是', pinyin: 'shì', meaning: '是的' },
    { char: '非', pinyin: 'fēi', meaning: '非常' },
    { char: '有', pinyin: 'yǒu', meaning: '拥有' },
    { char: '无', pinyin: 'wú', meaning: '无数' },
    { char: '能', pinyin: 'néng', meaning: '能够' },
    { char: '会', pinyin: 'huì', meaning: '会议' },
    { char: '要', pinyin: 'yào', meaning: '重要' },
    { char: '想', pinyin: 'xiǎng', meaning: '思想' },
    { char: '可', pinyin: 'kě', meaning: '可以' },
    { char: '以', pinyin: 'yǐ', meaning: '以后' },
    { char: '应', pinyin: 'yīng', meaning: '应该' },
    { char: '该', pinyin: 'gāi', meaning: '应该' },
    { char: '知', pinyin: 'zhī', meaning: '知道' },
    { char: '道', pinyin: 'dào', meaning: '道路' },
    { char: '明', pinyin: 'míng', meaning: '明白' },
    { char: '白', pinyin: 'bái', meaning: '明白' },
    { char: '记', pinyin: 'jì', meaning: '记得' },
    { char: '得', pinyin: 'dé', meaning: '得到' },
    { char: '忘', pinyin: 'wàng', meaning: '忘记' },
    { char: '记', pinyin: 'jì', meaning: '记录' },
    { char: '工', pinyin: 'gōng', meaning: '工人' },
    { char: '农', pinyin: 'nóng', meaning: '农民' },
    { char: '兵', pinyin: 'bīng', meaning: '士兵' },
    { char: '师', pinyin: 'shī', meaning: '老师' },
    { char: '生', pinyin: 'shēng', meaning: '学生' },
    { char: '医', pinyin: 'yī', meaning: '医生' },
    { char: '护', pinyin: 'hù', meaning: '护士' },
    { char: '司', pinyin: 'sī', meaning: '司机' },
    { char: '机', pinyin: 'jī', meaning: '飞机' },
    { char: '警', pinyin: 'jǐng', meaning: '警察' },
    { char: '察', pinyin: 'chá', meaning: '观察' },
    { char: '学', pinyin: 'xué', meaning: '学校' },
    { char: '校', pinyin: 'xiào', meaning: '学校' },
    { char: '医', pinyin: 'yī', meaning: '医院' },
    { char: '院', pinyin: 'yuàn', meaning: '医院' },
    { char: '商', pinyin: 'shāng', meaning: '商店' },
    { char: '店', pinyin: 'diàn', meaning: '店铺' },
    { char: '公', pinyin: 'gōng', meaning: '公园' },
    { char: '园', pinyin: 'yuán', meaning: '花园' },
    { char: '动', pinyin: 'dòng', meaning: '动物' },
    { char: '物', pinyin: 'wù', meaning: '物品' },
    { char: '影', pinyin: 'yǐng', meaning: '电影' },
    { char: '图', pinyin: 'tú', meaning: '图书' },
    { char: '书', pinyin: 'shū', meaning: '书籍' },
    { char: '馆', pinyin: 'guǎn', meaning: '图书馆' },
    { char: '过', pinyin: 'guò', meaning: '过去' },
    { char: '去', pinyin: 'qù', meaning: '过去' },
    { char: '现', pinyin: 'xiàn', meaning: '现在' },
    { char: '在', pinyin: 'zài', meaning: '存在' },
    { char: '将', pinyin: 'jiāng', meaning: '将来' },
    { char: '来', pinyin: 'lái', meaning: '未来' },
    { char: '以', pinyin: 'yǐ', meaning: '以前' },
    { char: '前', pinyin: 'qián', meaning: '以前' },
    { char: '已', pinyin: 'yǐ', meaning: '已经' },
    { char: '经', pinyin: 'jīng', meaning: '经过' },
    { char: '正', pinyin: 'zhèng', meaning: '正在' },
    { char: '要', pinyin: 'yào', meaning: '将要' },
    { char: '比', pinyin: 'bǐ', meaning: '比较' },
    { char: '更', pinyin: 'gèng', meaning: '更加' },
    { char: '最', pinyin: 'zuì', meaning: '最好' },
    { char: '和', pinyin: 'hé', meaning: '和平' },
    { char: '跟', pinyin: 'gēn', meaning: '跟着' },
    { char: '同', pinyin: 'tóng', meaning: '相同' },
    { char: '不', pinyin: 'bù', meaning: '不同' },
    { char: '一', pinyin: 'yī', meaning: '一样' },
    { char: '样', pinyin: 'yàng', meaning: '样子' },
    { char: '是', pinyin: 'shì', meaning: '是非' },
    { char: '非', pinyin: 'fēi', meaning: '非常' },
    { char: '有', pinyin: 'yǒu', meaning: '没有' },
    { char: '无', pinyin: 'wú', meaning: '无论' },
    { char: '能', pinyin: 'néng', meaning: '能力' },
    { char: '会', pinyin: 'huì', meaning: '学会' },
    { char: '要', pinyin: 'yào', meaning: '需要' },
    { char: '想', pinyin: 'xiǎng', meaning: '想念' },
    { char: '可', pinyin: 'kě', meaning: '可爱' },
    { char: '以', pinyin: 'yǐ', meaning: '可以' },
    { char: '应', pinyin: 'yìng', meaning: '反应' },
    { char: '该', pinyin: 'gāi', meaning: '应该' },
    { char: '知', pinyin: 'zhī', meaning: '知识' },
    { char: '道', pinyin: 'dào', meaning: '知道' },
    { char: '明', pinyin: 'míng', meaning: '明天' },
    { char: '白', pinyin: 'bái', meaning: '白色' },
    { char: '记', pinyin: 'jì', meaning: '记忆' },
    { char: '得', pinyin: 'de', meaning: '跑得' },
    { char: '忘', pinyin: 'wàng', meaning: '难忘' },
    { char: '记', pinyin: 'jì', meaning: '笔记' },
    { char: '工', pinyin: 'gōng', meaning: '工作' },
    { char: '农', pinyin: 'nóng', meaning: '农村' },
    { char: '兵', pinyin: 'bīng', meaning: '当兵' },
    { char: '师', pinyin: 'shī', meaning: '师傅' },
    { char: '生', pinyin: 'shēng', meaning: '生活' },
    { char: '医', pinyin: 'yī', meaning: '中医' },
    { char: '护', pinyin: 'hù', meaning: '保护' },
    { char: '司', pinyin: 'sī', meaning: '公司' },
    { char: '机', pinyin: 'jī', meaning: '机会' },
    { char: '警', pinyin: 'jǐng', meaning: '警告' },
    { char: '察', pinyin: 'chá', meaning: '察觉' }
  ]
};

function getCharsByLevel(level) {
  const levelKey = `level${level}`;
  return ChineseChars[levelKey] || [];
}

function getCharsGroupedByLevel(level, groupSize = 10) {
  const chars = getCharsByLevel(level);
  const groups = [];
  for (let i = 0; i < chars.length; i += groupSize) {
    groups.push(chars.slice(i, i + groupSize));
  }
  return groups;
}

function getTotalLevels() {
  return Object.keys(ChineseChars).length;
}
